using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StrangeServerCSharp
{
    public enum CellType
    {
        Nothing = 0,
        Gate = 30,
        VolcanoBackground = 31,
        Background = 32,
        BackgroundWithLightTraces = 33,
        BackgroundWithHeavyTraces = 34,
        Road = 35,
        GoldenRoad = 36,
        BuildingDoor = 37,
        BuildingBorder = 38,
        PolymerRoad = 39,
        BlackBoulder1 = 40,
        BlackBoulder2 = 41,
        BlackBoulder3 = 42,
        MetalBoulder1 = 43,
        MetalBoulder2 = 44,
        MetalBoulder3 = 45,
        QuadBlock = 48,
        Support = 49,
        LivingAquaCrystal = 50,
        LivingRedCrystal = 51,
        LivingPurpleCrystal = 52,
        LivingBlackCrystal = 53,
        LivingWhiteCrystal = 54,
        LivingRainbowCrystal = 55,
        WhiteSand = 60,
        DarkWhiteSand = 61,
        RustySand = 62,
        DarkRustySand = 63,
        BlackSand = 64,
        DarkBlackSand = 65,
        GrayAcid = 66,
        PurpleAcid = 67,
        Pearl = 68,
        UnknownRock1 = 69,
        UnknownRock2 = 70,
        GreenCrystalX = 71,
        BlueCrystalX = 72,
        RedCrystalX = 73,
        AquaCrystalX = 74,
        PurpleCrystalX = 75,
        UnknownRock3 = 76,
        UnknownRock4 = 77,
        UnknownRock5 = 78,
        UnknownRock6 = 79,
        MilitaryBlockFrame = 80,
        MilitaryBlock = 81,
        MilitaryBlockSand = 82,
        TeleportBlock = 83,
        PassiveAcid = 86,
        SuperRainbowCrystal = 87,
        Skull = 88,
        Box = 90,
        Lava = 91,
        Boulder1 = 92,
        Boulder2 = 93,
        Boulder3 = 94,
        LivingActiveAcid = 95,
        CorrosiveActiveAcid = 96,
        BlueSand = 97,
        DarkBlueSand = 98,
        YellowSand = 99,
        DarkYellowSand = 100,
        GreenBlock = 101,
        YellowBlock = 102,
        Rock = 103,
        Border = 104,
        RedBlock = 105,
        InvisibleBlock = 106,
        GreenCrystal = 107,
        RedCrystal = 108,
        BlueCrystal = 109,
        PurpleCrystal = 110,
        WhiteCrystal = 111,
        AquaCrystal = 112,
        HeavyRock = 113,
        BlackRock = 114,
        LivingBlackRock = 115,
        LivingBlueCrystal = 116,
        RedRock = 117,
        AcidRock = 118,
        HypnoRock = 119,
        GoldenRock = 120,
        DeepRock = 121,
        GRock = 112
    }
}
